config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,    :validate => true
	attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,  :validate => true
	attribute :nickname, :captcha => true

	def headers
		{
		:subject => "Contact Form",
		:to => "warren.chan.kw@gmail.com" ,
		:from => %("#{name}" <#{email}>)
	}

    end
end

app/models/post.rb
class Post < ApplicationRecord
	 extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
   
	 has_attached_file :image, styles: {medium:'220x220#'}
	 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	 has_attached_file :image2, styles: {medium:'220x220#'}
	 validates_attachment_content_type :image2, content_type: /\Aimage\/.*\z/
	 has_attached_file :image3, styles: {medium:'220x220#'}
	 validates_attachment_content_type :image3, content_type: /\Aimage\/.*\z/
	 extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create 
         @contact = Contact.new(params[:contact])
         @contact.request = request
         if @contact.deliver
         	flash.now[:error] = nil
         else
         	flash.now[:error] = 'Cannot send message.'
         	render :new
         end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@posts = Post.all.order("created_at desc").paginate(:page => params[:page], :per_page => 1)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Kimochi, Warren! Your post was successfully saved!"
		else 
			render 'new', notice: "Opps, Master Warren! I can't save the post."
		end
	end

	def show
       
    end

    def edit
    end

    def update
    	if @post.update post_params
    		redirect_to @post, notice: "Awesome! Your post was successfully saved!"
    	else
    		render 'edit'
    	end
    end

    def destroy
    	@post.destroy
    	redirect_to posts_path 
    end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end 

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]

	def index
        @projects = Project.all.order("created_at desc")
	end

    def new
    	@project=Project.new
    end

    def create
     	@project=Project.new project_params     

        if  @project.save
            redirect_to @project, notice: "Good Job Master! I saved your project!"
        else
            render 'new' 
        end
    end

    def show
    end

    def edit

    end

    def update
    	if @project.update project_params
    		redirect_to @project, notice: "Good Job Master! I updated your project!"
    	else
    		render 'edit'
    	end
    end

    def destroy
    	@project.destroy
    	redirect_to projects_path
    end

    private

    def find_project
        @project = Project.friendly.find(params[:id])
    end

    def project_params
       params.require(:project).permit(:title, :description, :link, :image, :image2, :image3, :slug)      
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
       @posts = Post.all.limit(3).order("created_at desc")
       @projects = Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
      class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
        CodeRay.scan(code, language).div
    end
end

def markdown(text)
    coderayified = CodeRayify.new(filter_html: true,  hard_wrap: true)
    options = {
        :fenced_code_blocks => true,
        :no_intra_emphasis => true,
        :autolink => true,
        :strikethrough => true,
        :lax_html_blocks => true,
        :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
 end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">You Can Ask Me Anything!</h1>



  <div class="skinny_wrapper wrapper_padding">
  	<%= form_for @contact do |f| %>
  	<%= f.label :name %><br>
  	<%= f.text_field :name, required: true %> 

  	<br> 
    <%= f.label :email %><br>
  	<%= f.text_field :email, required: true %> 

  	<br> 
    <%= f.label :message %><br>
  	<%= f.text_area :message, as: :text %> 


    <div class = "hidden">
    <%= f.label :nickname %><br>
  	<%= f.text_field :nickname, hint: 'leave this field blank' %> 

    </div>

    <%= f.submit 'Send Message', class:"button" %>
    <% end %>


 
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Warren Chan - Software Engineer</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header id="main_navigation" class="clearfix">
    		<%= link_to "Warren Chan", root_path, class: "name" %>
    		<nav>
    			<%= link_to "Posts", posts_path %>
    			<%= link_to "Projects", projects_path %>
          <%= link_to "Resume", "/myresume.pdf" %>
          <%= link_to "Contact", new_contact_path %>

          <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% end %>
             
    		</nav>
    	</header>
       <% if notice %>
        <p class="notice"><%= notice %></p>
        <% elsif alert %>
       <p class="alert"><%= alert %></p>
      <% end %>

    <%= yield %>

    <footer id="main_footer">
            <p class="copyright">&copy; 2018 warrenkwchan</p>
            <nav>
            <a href="https://twitter.com/warrenkwchan" target='_blank'><i class="fab fa-twitter-square"></i></a>
            <a href="https://www.linkedin.com/in/warren-chan-00431412b/" target='_blank'><i class="fab fa-linkedin"></i></a>
            <a href="https://github.com/warrenkwchan" target='_blank'><i class="fab fa-github"></i></a>
        </nav>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
shortname = 'TrollBlog';
this.page.title= '<%= @post.title %>';
this.page.url = '<%= 'http://localhost:3000' %><%= url_for([@post, {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.title %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};




(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://warrens-portfolio.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving: </h2>
<ul>
	<% @post.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "Write your articale here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>


<div class="skinny_wrapper wrapper_padding">

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Posts History</h1>

       <div id="posts_wrapper" class="skinny_wrapper">
       	<% @posts.each do |post| %>
          <div class="post">
             	<p class="date"><%= post.created_at.strftime('%A, %B %d') %> </p>
             	<h2><a href="#"><%= link_to post.title, post %></a></h2>
             	<hr>
             </div>

       	<% end %>
                    
</div>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Posts</h1>


<div class="skinny_wrapper wrapper_padding">



<%= render 'form' %>
</div>

app/views/posts/show.html.erb
   <div id="post_show_content" class="skinny_wrapper wrapper_padding">
            <header>
                <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
                <h1><%= @post.title %></h1>
                <hr>
            </header>
            <div id="content">
            	<%= markdown @post.content %>
            </div>

            <% if user_signed_in? %>
            <div id="admin_links">
                <%= link_to "Edit Posts", edit_post_path(@post) %>
                <%= link_to "Delete Posts", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
            <% end %>

            <hr>

            <div id="share_box">
            	<p>Share The DO List</p>

            	<!-- Twitter -->
            	<a onclick="javascript:window.open('https://twitter.com/intent/tweet?text=<%= @post.title %> by @warrenkwchan - <%= url_for(post_url) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-twitter-square"></i></a>
            	<!-- Facebook -->
            	<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for(post_url) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-facebook"></i></a>
            	<!-- Google Plus -->
            	<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for(post_url) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-google-plus-square"></i></a>

            </div>

            <hr>

            <%= render 'disqus'%>
        </div>

        

app/views/projects/_form.html.erb
<%= form_for(@project, multipart: true) do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count, "error") %> prevented this post from saving: </h2>
<ul>
	<% @project.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :description %><br>
<%= f.text_area :description %>

<br>
<br>


<%= f.label :image %><br>
<%= f.file_field :image %>

<br>
<br>

<%= f.label :image2%><br>
<%= f.file_field :image2 %>

<br>
<br>

<%= f.label :image3 %><br>
<%= f.file_field :image3 %>

<br>
<br>


<%= f.label :link %><br>
<%= f.text_field :link %>

<br>
<br>


<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">EDIT PROJECT</h1>
<div class="skinny_wrapper wrapper_padding">
     
     <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I've Built</h1>

       <div id="posts_wrapper" class="skinny_wrapper">
       	<% @projects.each do |project| %>
          <div class="post">
             	<p class="date"><%= project.created_at.strftime('%A, %B %d') %> </p>
             	<h2><a href="#"><%= link_to project.title, project %></a></h2>
             	<hr>
             </div>

       	<% end %>
                    
</div>

app/views/projects/new.html.erb
<h1 id="page_title">NEW PROJECT</h1>

<div class="skinny_wrapper wrapper_padding">
    
     <%= render 'form' %>
</div>

app/views/projects/show.html.erb
   <div id="post_show_content" class="skinny_wrapper wrapper_padding">
            <header>
                <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
                <h1><%= @project.title %></h1>
                <hr>
            </header>
            <div id="content">
            	
               <% if @project.image.present? %>
               <center> <%= image_tag @project.image.url(:medium) %>.   
                    <% if @project.image2.present? %>
                        <%= image_tag @project.image2.url(:medium) %>
                        <% end %>
                          <% if @project.image3.present? %>
                        <%= image_tag @project.image3.url(:medium) %> 
                        <% end %>
                </center>
                <% end %>

                <%= markdown @project.description %>
                 
                <div class="button_wrapper">
                 <% if @project.link.present? %>
                <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
                <% end %>
            </div>
            </div>

            <% if user_signed_in? %>
            <div id="admin_links">
                <%= link_to "Edit", edit_project_path(@project)%>
             <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"}%>
            </div>
            <% end %>

            

            <hr>
            
        </div>

app/views/welcome/index.html.erb
 <div class="wrapper wrapper_padding clearfix">
           <div class = "col-1 about homepage_content">
               <h2>About</h2>
               <hr>
               <p>I'm a software engineer &amp; student living in Seattle, WA United States.
               </p>
               <p>Currently I work at Amazon's ordering team responsible for the whole ordering workflow after checkout for all retail businesses.
                I graduated from university in 2019 double majoring in Computer Science and Statistics. I spend my free time making web and iOS applications;
                learning and applying concepts about Machine Learning and Distributed System. I also love being a TA for
                Algorithm, Data Structure, and Software Engineering classes at school  <a href='https://www.cs.ubc.ca/'> UBC Computer Science</a>
               </p>.
               <p> You can find me on Twitter, Facebook, Instagram, professional details on LinkedIn, and sharing some
                code on Github.
            </p>
               
           </div>
           <div class ="col-2 homepage_content">
             <h2>  Recent Posts </h2>
             <hr>

             <% @posts.each do |post| %>
             <h3><a href="#"><%= link_to post.title, post%></a></h3>
             <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>

             <% end %>
           </div>
           <div class ="col-3 homepage_content">
            <h2>  Recent Projects </h2>
             <hr>
             <% @projects.each do |project| %>
             <h3><a href="#"><%= link_to project.title, project%></a></h3>
             <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>

             <% end %>
             

           </div>
        </div>